### PR TITLE
feat(ci): added github actions

### LINKED ISSUE #9: add github actions to build middleware
add github action to ensure that no commit breaks the library.

### PR DESCRIPTION
**Pull request by MASTERCHIEF011**
# Issue Related with PR
- fixes #9

### CODE REVIEW

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
add action to test if package builds or not.

**Comment by MASTERCHIEF011** [comment]
> add action to test if package builds or not.

okay

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
action still does not ensure that package builds. 

the action is empty.

**Review by YashKumarVerma — APPROVED** [review]

**Comment by YashKumarVerma** [comment]
thanks !

**Pull request merged**
